### ISSUE TITLE
Avoid break inside sidebar and example blocks

### ISSUE THREAD

**Issue by ggrossetie** [ggrossetie/asciidoctor-web-pdf#374]
```css
.sidebarblock {
  break-inside: avoid;
}

.exampleblock {
  break-inside: avoid;
}
```
